/**
 * Exam Loader - Dynamically loads exams from JSON files
 * No more hardcoded exam-data.js files!
 *
 * This module automatically:
 * - Discovers exam directories in user-content/exams/
 * - Loads dump.json and metadata.json from each directory
 * - Checks localStorage for imported exams
 * - Populates window.userExams with all available exams
 */

// Initialize user exams container
window.userExams = window.userExams || {};

// Main loader function
window.loadAllExams = async function() {
    console.log('🔍 Discovering exams...');

    // Try to discover exam directories automatically
    let examDirs = [];

    try {
        const response = await fetch('user-content/exams/');
        if (response.ok) {
            const text = await response.text();
            // Parse directory listing
            const parser = new DOMParser();
            const doc = parser.parseFromString(text, 'text/html');
            const links = doc.querySelectorAll('a');
            examDirs = Array.from(links)
                .map(a => {
                    const href = a.getAttribute('href');
                    if (!href) return null;
                    // Extract directory name (remove trailing slash)
                    const match = href.match(/([^\/]+)\/?$/);
                    return match ? match[1] : null;
                })
                .filter(name => name && name !== '..' && !name.includes('.') && name !== 'exams');

            console.log('✓ Auto-discovered exam directories:', examDirs);
        }
    } catch (e) {
        console.log('⚠️  Auto-discovery not available, will check localStorage only');
    }

    // Load each exam from dump.json
    const loadPromises = examDirs.map(async (examId) => {
        try {
            // Fetch dump.json
            const dumpResponse = await fetch(`user-content/exams/${examId}/dump.json`);
            if (!dumpResponse.ok) {
                console.log(`✗ ${examId}: dump.json not found`);
                return;
            }

            let questions = await dumpResponse.json();

            // Handle both formats: [{...}] and {questions: [...]}
            if (questions.questions) {
                questions = questions.questions;
            }

            // Try to fetch metadata.json (optional)
            let metadata = null;
            try {
                const metadataResponse = await fetch(`user-content/exams/${examId}/metadata.json`);
                if (metadataResponse.ok) {
                    metadata = await metadataResponse.json();
                }
            } catch (e) {
                // Metadata is optional, will be generated by examManager
            }

            // Store in window.userExams
            window.userExams[examId] = {
                questions: questions,
                metadata: metadata
            };

            console.log(`✓ Loaded ${examId}: ${questions.length} questions`);
        } catch (error) {
            console.error(`✗ Failed to load ${examId}:`, error);
        }
    });

    // Wait for all exams to load
    await Promise.all(loadPromises);

    // Also check localStorage for imported exams
    console.log('🔍 Checking localStorage for imported exams...');
    for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        if (key && key.startsWith('custom_') && key.endsWith('_questions')) {
            const examId = key.replace('custom_', '').replace('_questions', '');
            if (!window.userExams[examId]) {
                try {
                    const questions = JSON.parse(localStorage.getItem(key));
                    const metadataKey = `exam_metadata_${examId}`;
                    const metadata = localStorage.getItem(metadataKey)
                        ? JSON.parse(localStorage.getItem(metadataKey))
                        : null;

                    window.userExams[examId] = {
                        questions: questions,
                        metadata: metadata
                    };
                    console.log(`✓ Loaded ${examId} from localStorage: ${questions.length} questions`);
                } catch (e) {
                    console.error(`✗ Failed to load ${examId} from localStorage:`, e);
                }
            }
        }
    }

    console.log('✅ All exams loaded:', Object.keys(window.userExams));
    return window.userExams;
};

// Export as a promise for async/await usage
window.examsLoadedPromise = window.loadAllExams();
