/**
 * Exam Loader - Dynamically loads exams from JSON files
 * No more hardcoded exam-data.js files!
 *
 * This module automatically:
 * - Discovers exam directories in user-content/exams/
 * - Loads dump.json and metadata.json from each directory
 * - Checks localStorage for imported exams
 * - Populates window.userExams with all available exams
 */

// Initialize user exams container
window.ExamApp = window.ExamApp || {};
window.ExamApp.userExams = window.ExamApp.userExams || {};
window.userExams = window.ExamApp.userExams; // backwards compat

// Main loader function
window.ExamApp.loadAllExams = async function() {
    console.log('🔍 Discovering exams...');

    // Try to discover exam directories automatically
    let examDirs = [];

    try {
        // Try JSON index first (if server provides one)
        const indexResponse = await fetch('user-content/exams/index.json');
        if (indexResponse.ok) {
            const examList = await indexResponse.json();
            if (Array.isArray(examList)) {
                examDirs = examList;
                console.log('✓ Loaded exam list from index.json:', examDirs);
            }
        }
    } catch (e) {
        // index.json not available, fall through
    }

    if (examDirs.length === 0) {
        try {
            // Fallback: try to parse directory listing HTML
            const response = await fetch('user-content/exams/');
            if (response.ok) {
                const html = await response.text();
                const parser = new DOMParser();
                const doc = parser.parseFromString(html, 'text/html');
                const links = doc.querySelectorAll('a');
                const dirs = [];
                links.forEach(link => {
                    const name = link.textContent.trim().replace(/\/$/, '');
                    if (name && name !== '..' && name !== '.' && !name.includes('.') && name.length > 0) {
                        dirs.push(name);
                    }
                });
                examDirs = dirs;
                if (examDirs.length > 0) {
                    console.log('✓ Auto-discovered exam directories:', examDirs);
                }
            }
        } catch (e) {
            console.log('Directory listing not available, using localStorage exams only');
        }
    }

    // Load each exam from dump.json
    const loadPromises = examDirs.map(async (examId) => {
        try {
            // Fetch dump.json
            const dumpResponse = await fetch(`user-content/exams/${examId}/dump.json`);
            if (!dumpResponse.ok) {
                console.log(`✗ ${examId}: dump.json not found`);
                return;
            }

            let questions = await dumpResponse.json();

            // Handle both formats: [{...}] and {questions: [...]}
            if (questions.questions) {
                questions = questions.questions;
            }

            // Try to fetch metadata.json (optional)
            let metadata = null;
            try {
                const metadataResponse = await fetch(`user-content/exams/${examId}/metadata.json`);
                if (metadataResponse.ok) {
                    metadata = await metadataResponse.json();
                }
            } catch (e) {
                // Metadata is optional, will be generated by examManager
            }

            // Store in window.userExams
            window.userExams[examId] = {
                questions: questions,
                metadata: metadata
            };

            console.log(`✓ Loaded ${examId}: ${questions.length} questions`);
        } catch (error) {
            console.error(`✗ Failed to load ${examId}:`, error);
        }
    });

    // Wait for all exams to load
    await Promise.all(loadPromises);

    // Also check localStorage for imported exams
    console.log('🔍 Checking localStorage for imported exams...');
    const len = localStorage.length;
    for (let i = 0; i < len; i++) {
        const key = localStorage.key(i);
        if (key && key.startsWith('custom_') && key.endsWith('_questions')) {
            const examId = key.replace('custom_', '').replace('_questions', '');
            if (!window.userExams[examId]) {
                try {
                    const questions = JSON.parse(localStorage.getItem(key));
                    const metadataKey = `exam_metadata_${examId}`;
                    const metadataRaw = localStorage.getItem(metadataKey);
                    const metadata = metadataRaw ? JSON.parse(metadataRaw) : null;

                    window.userExams[examId] = {
                        questions: questions,
                        metadata: metadata
                    };
                    console.log(`✓ Loaded ${examId} from localStorage: ${questions.length} questions`);
                } catch (e) {
                    console.error(`✗ Failed to load ${examId} from localStorage:`, e);
                }
            }
        }
    }

    console.log('✅ All exams loaded:', Object.keys(window.userExams));
    return window.userExams;
};
window.loadAllExams = window.ExamApp.loadAllExams; // backwards compat

// Export as a promise for async/await usage
window.ExamApp.examsLoadedPromise = window.ExamApp.loadAllExams();
window.examsLoadedPromise = window.ExamApp.examsLoadedPromise; // backwards compat
